name: dart_adif
description: Read and write ADIF (Amateur Radio Data Interchange Format) files.
version: 1.0.2
homepage: https://github.com/adrianboyko/dart-adif

environment:
  sdk: '>=2.12.0 <3.2.0'

dependencies:
  charcode: ^1.3.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  coverage: ^1.7.2